name: Deploy Jupyter Book to Netlify

on:
  push:
    branches:
      - main  # 這將在每次推送到 main 分支時觸發

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 你可以根據需要調整 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter-book

      - name: Build Jupyter Book
        run: jupyter-book build .

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # 安裝 netlify-cli
          npm install -g netlify-cli
          # 部署到 Netlify
          netlify deploy --dir=_build/html --prod --site=$NETLIFY_SITE_ID
