name: Deploy Jupyter Book to Minify

on:
  push:
    branches:
      - main  # 這將在每次推送到 main 分支時觸發

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 你可以根據需要調整 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter-book

      - name: Build Jupyter Book
        run: jupyter-book build .

      - name: Deploy to Minify
        env:
          MINIFY_API_KEY: ${{ secrets.MINIFY_API_KEY }}  # 確保在 GitHub Secrets 中配置 Minify API 金鑰
        run: |
          # 進入 _build/html 目錄
          cd _build/html
          # 壓縮文件為 ZIP 包
          zip -r site.zip .
          # 使用 Minify API 上傳 ZIP 包
          curl -X POST -H "Authorization: Bearer $MINIFY_API_KEY" -F "file=@site.zip" https://api.minify.com/v1/deploy
